autoSwitchLanguage = true
checkModPackTranslationUpdate = true
autoDownloadVMTranslationPack = true
autoInstallVMTranslationPack = true
displayTips = true
playerNameCheck = true
modPackTranslationUpdateCheckUrl = "https://vmct-cn.top/modpacks/cottage/update.txt"
modPackTranslationUrl = "https://vmct-cn.top/modpacks/cottage/"
tipsUrl = "https://vmct-cn.top/tips.txt"
modPackTranslationVersion = "1.0"
tipsMinutes = 25
traslationPackName = "VM汉化组模组汉化包1.19"
traslationPackUrl = "https://cdn.modrinth.com/data/IDWIdXwS/versions/acZy8zAY/VM汉化组模组汉化包1.19"
nameUrl = "https://vmct-cn.top/name.json"
